master:
  push:
    - env:
        DOCKER_LOGIN: docker login -u frontend-1695547599036 -p 12c728f79805a84f382f353850a97e730a4997d5 wteam-khai-docker.pkg.coding.net
        HOST: 111.229.66.85:22    #服务器ip
        HOST_PASSWORD: 8wy,9{F%gB3d  #服务器密码
        APP_MANAGER_NAME: wine-mall-system   #服务名称 项目+服务名  客户端
        MANAGER_PORT: 8003   #客户端端口
      docker:
        image: node:12
        volumes:
          - /root/.npm:copy-on-write
      services:
        # 流水线中启用 docker 服务
        - docker
      stages:
        - name: docker login
          script: ${DOCKER_LOGIN}
          #docker制品构建创建对应镜像
        - name: docker build
          script:
            - docker build -t wteam-khai-docker.pkg.coding.net/zaolunzi/frontend/${APP_MANAGER_NAME}:latest .
          #将docker制品推送到制品库
        - name: docker push
          script:
            - docker push wteam-khai-docker.pkg.coding.net/zaolunzi/frontend/${APP_MANAGER_NAME}:latest
        - name: start 部署并重启
          image: appleboy/drone-ssh # SSH工具镜像
          settings:
            host: ${HOST} # 远程连接地址
            username: root # 远程连接账号
            password: ${HOST_PASSWORD}
            port: 22 # 远程连接端口
            command_timeout: 5m # 远程执行命令超时时间
            script:
              - docker stop ${APP_MANAGER_NAME}   #部署客户端
              - docker rm ${APP_MANAGER_NAME}
              - docker image rm ${APP_MANAGER_NAME}
              - docker login -u frontend-1695547599036 -p 12c728f79805a84f382f353850a97e730a4997d5 wteam-khai-docker.pkg.coding.net
              - docker pull wteam-khai-docker.pkg.coding.net/zaolunzi/frontend/${APP_MANAGER_NAME}:latest
#       #  -p: 指定端口映射; -e : 设置环境变量； -v: 绑定一个卷;  -d: 后台运行容器，并返回容器ID；
              - docker run -p ${MANAGER_PORT}:80 --name ${APP_MANAGER_NAME} -e TZ="Asia/Shanghai" -v /etc/localtime:/etc/localtime -d wteam-khai-docker.pkg.coding.net/zaolunzi/frontend/${APP_MANAGER_NAME}:latest
        # - name: scp files
        #   image: appleboy/drone-scp
        #   volumes: #将主机的shell脚本与容器共享
        #     - name: host-mount
        #       path: /data
        #   settings:
        #     host: 47.109.28.61
        #     username: root
        #     password: cq@YG88888888
        #     port: 22
        #     rm: true
        #     source:
        #       - ./dist
        #     target:
        #       - /data/sh/
        #   environment:
        #     AUTO_CREATE_DIR: "true" # 自动创建目标目录

      # - stages:
      #   - name: spring-start 部署并重启
      #     image: appleboy/drone-ssh # SSH工具镜像
      #     settings:
      #       host: 47.99.90.88 # 远程连接地址
      #       username: root # 远程连接账号
      #       password:
      #         from_secret: 47.99.90.88_password # 从Secret中读取SSH密码
      #       port: 22 # 远程连接端口
      #       command_timeout: 5m # 远程执行命令超时时间
      #       script:
      #         - cd /data/sh # 进入宿主机构建目录
      #         - chmod +x develop.sh # 更改为可执行脚本
      #         - ./develop.sh  # 运行脚本打包应用镜像并运行
      #     when:
      #       event:
      #         - push # 当代码 push 时才重新上传
